name: Mirror Repo with Timeout Fix

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Create credentials file
        run: |
          echo "${{ secrets.REPO_CREDENTIALS }}" > repo_credentials.txt

      - name: Read repo addresses
        run: |
          SOURCE_REPO=$(sed -n '1p' repo_credentials.txt)
          TARGET_REPO=$(sed -n '2p' repo_credentials.txt)
          echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
          echo "TARGET_REPO=$TARGET_REPO" >> $GITHUB_ENV

      - name: Clean up existing directory
        run: |
          if [ -d "source_repo" ]; then
            rm -rf source_repo
          fi

      - name: Clone source repository
        run: |
          git clone --mirror ${{ env.SOURCE_REPO }} source_repo
          cd source_repo

      - name: Configure Git timeout and buffer
        run: |
          cd source_repo
          # 增加HTTP超时时间（10分钟）
          git config http.postBuffer 524288000  # 500MB缓冲区
          git config http.timeout 600
          git config http.keepAlive true

      - name: Push branches in batches
        run: |
          cd source_repo
          git remote add target ${{ env.TARGET_REPO }}
          
          # 获取所有分支并分批推送（每次5个分支，避免单次推送过大）
          branches=$(git branch -r | grep -v 'HEAD' | sed 's/origin\///' | tr '\n' ' ')
          echo "Branches to push: $branches"
          
          # 分批推送函数
          batch_push() {
            local batch=()
            for branch in $branches; do
              batch+=("$branch")
              if [ ${#batch[@]} -eq 5 ]; then
                echo "Pushing batch: ${batch[*]}"
                git push target "${batch[@]}" || {
                  echo "Failed to push batch, retrying..."
                  git push target "${batch[@]}"  # 重试一次
                }
                batch=()
              fi
            done
            # 推送剩余分支
            if [ ${#batch[@]} -gt 0 ]; then
              echo "Pushing remaining: ${batch[*]}"
              git push target "${batch[@]}"
            fi
          }
          
          batch_push

      - name: Push tags
        run: |
          cd source_repo
          # 单独推送标签，同样增加重试机制
          git push target --tags || git push target --tags
